steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nwsl-api:$SHORT_SHA', '.']

images:
  - 'gcr.io/$PROJECT_ID/nwsl-api:$SHORT_SHA'

timeout: 1200s

# Customize further as deployment automation matures.
